version: "3.3"

services:
  app:
    container_name: mirror-status-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_JSON_URL=
      - CONFIG_ENV_URL=
    command: python3 main.py
    restart: on-failure
